name: Tests

on: [ push, pull_request, workflow_dispatch ]

env:
  PORT: 3000
  NEXT_PUBLICE_ENVIRONMENT: testnet

jobs:
  report:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.4

      - name: Install Node dependencies
        run: yarn install

      - name: TSLint
        run: yarn lint
